export const ALLOWED_AGENT_ORDER = [
  'Average Austin',
  'No Problem Nancy',
  'Switchover Steve',
  'Not Interested Nick',
  'DIY Dave',
  'Too Expensive Tim',
  'Spouse Check Susan',
  'Busy Beth',
  'Renter Randy',
  'Skeptical Sam',
  'Just Treated Jerry',
  'Think About It Tina',
  'Veteran Victor',
  'I Already Have a Pest Guy',
  'I Don\'t Have Any Bugs',
  'How Much Is It?',
  'I Need to Talk to My Spouse',
  'I\'m Renting/Don\'t Own',
  'I Just Spray Myself',
  'Send Me Information',
  'We\'re Selling/Moving Soon',
  'I Have Pets/Kids - Worried About Chemicals',
  'Bad Timing - Call Me Back Later',
  'I Already Have Internet',
  'I\'m in a Contract',
  'I\'m Happy With What I Have',
  'I Just Signed Up',
  'I Don\'t Want to Deal With Switching',
  'My Internet Works Fine',
  'What\'s the Catch?',
  'I\'m Moving Soon',
  'My Roof is Fine',
  'I\'m Not Interested',
  'How Much Does a Roof Cost?',
  'I Just Had My Roof Done',
  'I\'ll Call You When I Need a Roof',
  'I Already Have Someone',
  'My Insurance Won\'t Cover It',
  'I\'m Selling Soon',
  'I Don\'t Trust Door-to-Door Roofers',
  'I\'m Not Interested in Solar',
  'Solar is Too Expensive',
  'How Much Does It Cost?',
  'My Electric Bill is Too Low',
  'What If It Doesn\'t Work?',
  'My Roof is Too Old',
  'I\'ve Heard Bad Things About Solar',
  'I Don\'t Qualify',
  'My Windows Are Fine',
  'That\'s Too Expensive',
  'I\'m Going to Get Multiple Quotes',
  'I Just Need One or Two Windows',
  'Just Got New Windows',
  'I\'m Selling/Moving Soon',
  'I\'ll Just Do It Myself',
  'What\'s Wrong With My Current Windows?',
  'I\'m Waiting Until...',
  'I Don\'t Trust Window Companies',
  'I\'m Not Interested',
  'Not the Right Time / Maybe Next Year',
  'The Karen',
  'Angry Indian',
] as const

export type AllowedAgentName = typeof ALLOWED_AGENT_ORDER[number]

export const ALLOWED_AGENT_SET = new Set<AllowedAgentName>(ALLOWED_AGENT_ORDER)

export const ORDER_LOOKUP = new Map<AllowedAgentName, number>(
  ALLOWED_AGENT_ORDER.map((name, index) => [name, index])
)

type BubbleDifficulty = 'Easy' | 'Moderate' | 'Hard' | 'Expert'
type BubbleColorVariant =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'quaternary'
  | 'quinary'
  | 'senary'
  | 'septenary'
  | 'octonary'
  | 'nonary'
  | 'denary'
  | 'duodenary'
  | 'undenary'
type CardDifficultyKey = 'easy' | 'moderate' | 'hard' | 'expert'

interface PersonaBubbleDetail {
  subtitle: string
  description: string
  difficulty: BubbleDifficulty
  color: BubbleColorVariant
  image?: string // Selection bubble image
  liveSessionImage?: string // Image shown during active conversation
}

interface PersonaCardDetail {
  age: number
  occupation: string
  location: string
  personality: string
  challengeLevel: number
  challengeLabel: string
  difficultyKey: CardDifficultyKey
  traits: string[]
  bestFor: string
  estimatedTime: string
  startingScore: number
  targetScore: number
  avatar: string
  color: string
  recommended?: boolean
  mostChallenging?: boolean
  elevenAgentId?: string
  elevenVoiceId?: string // Voice ID for TTS snippets - get from ElevenLabs agent configuration
}

interface PersonaMetadata {
  bubble: PersonaBubbleDetail
  card: PersonaCardDetail
}

export const PERSONA_METADATA: Record<AllowedAgentName, PersonaMetadata> = {
  'Average Austin': {
    bubble: {
      subtitle: 'Skeptical but Fair',
      description: 'Challenges pricing. Practice trust building.',
      difficulty: 'Moderate',
      color: 'primary',
      image: '/Austin No Backround.png', // Selection bubble (capital N, B)
      liveSessionImage: '/Austin Boss.png', // During live conversation
    },
    card: {
      age: 38,
      occupation: 'Works from Home',
      location: 'Round Rock, TX',
      personality: 'Skeptical but fair, direct communicator',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Asks direct questions about pricing and guarantees',
        'Detects pressure tactics immediately',
        'Terminates after three pricing deflections',
        'Pets and child safety are top priorities',
      ],
      bestFor: 'Building foundational objection handling and trust',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 70,
      avatar: '🏡',
      color: 'green',
      recommended: true,
      elevenAgentId: 'agent_7001k5jqfjmtejvs77jvhjf254tz',
    },
  },
  'No Problem Nancy': {
    bubble: {
      subtitle: 'Easy Agreement',
      description: 'Easily agrees. Practice smooth closes.',
      difficulty: 'Easy',
      color: 'secondary',
      image: '/Nancy Black No backround.png',
      liveSessionImage: '/No Problem Nancy Black.png',
    },
    card: {
      age: 42,
      occupation: 'Elementary School Teacher',
      location: 'Suburban neighborhood',
      personality: 'Warm, agreeable, and trusting',
      challengeLevel: 1,
      challengeLabel: 'Easy',
      difficultyKey: 'easy',
      traits: [
        'Agrees to most suggestions without pushback',
        'Appreciates friendly conversation',
        'Makes decisions quickly',
        'Great for practicing smooth closes',
      ],
      bestFor: 'Building confidence and perfecting your pitch flow',
      estimatedTime: '3-5 min',
      startingScore: 60,
      targetScore: 85,
      avatar: '😊',
      color: 'blue',
      recommended: true,
      elevenAgentId: 'agent_0101k6dvb96zejkv35ncf1zkj88m',
    },
  },
  'Switchover Steve': {
    bubble: {
      subtitle: 'Current Customer',
      description: 'Already serviced. Practice competitive positioning.',
      difficulty: 'Hard',
      color: 'tertiary',
      image: '/Already got it Alan no backround 2.png', // Selection bubble
      liveSessionImage: '/Already got it Alan landscape.png', // During live conversation
    },
    card: {
      age: 51,
      occupation: 'Accountant',
      location: 'Established neighborhood',
      personality: 'Loyal to current provider, needs strong reason to switch',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Satisfied with current pest control company',
        'Needs compelling reason to switch',
        'Asks about contract terms and cancellation',
        'Values consistency and reliability',
      ],
      bestFor: 'Competitive positioning and differentiation tactics',
      estimatedTime: '7-10 min',
      startingScore: 45,
      targetScore: 75,
      avatar: '🤝',
      color: 'purple',
      elevenAgentId: 'agent_9901k6dvcv32embbydd7nn0prdgq',
    },
  },
  'Not Interested Nick': {
    bubble: {
      subtitle: 'Quick Dismissal',
      description: 'Wants to end conversation. Practice pattern interrupts.',
      difficulty: 'Expert',
      color: 'quaternary',
      image: '/Not Intersted Nick no backround 2.png',
      liveSessionImage: '/Not Interested Nick.png',
    },
    card: {
      age: 35,
      occupation: 'Software Engineer',
      location: 'Urban townhome',
      personality: 'Dismissive, busy, low patience for sales',
      challengeLevel: 5,
      challengeLabel: 'Expert',
      difficultyKey: 'expert',
      traits: [
        'Says "not interested" within first 10 seconds',
        'Tries to close door quickly',
        'Needs immediate value hook to stay engaged',
        'Responds to pattern interrupts and curiosity',
      ],
      bestFor: 'Mastering opening hooks and pattern interrupts',
      estimatedTime: '2-6 min',
      startingScore: 30,
      targetScore: 65,
      avatar: '🚪',
      color: 'red',
      mostChallenging: true,
      elevenAgentId: 'agent_7601k6dtrf5fe0k9dh8kwmkde0ga',
    },
  },
  'DIY Dave': {
    bubble: {
      subtitle: 'Self-Sufficient',
      description: 'Prefers DIY. Practice professional value.',
      difficulty: 'Hard',
      color: 'quinary',
      image: '/DIY DAVE no backround 2.png', // Selection bubble
      liveSessionImage: '/DIY DAVE.png', // During live conversation
    },
    card: {
      age: 48,
      occupation: 'Contractor',
      location: 'Ranch-style home',
      personality: 'Handy, self-reliant, skeptical of paying for services',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Believes he can handle pest control himself',
        'Knows about store-bought products',
        'Questions the value of professional service',
        'Responds to expertise and time-saving benefits',
      ],
      bestFor: 'Demonstrating professional value over DIY',
      estimatedTime: '6-9 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '🔧',
      color: 'orange',
      elevenAgentId: 'agent_1701k6dvc3nfejmvydkk7r85tqef',
    },
  },
  'Too Expensive Tim': {
    bubble: {
      subtitle: 'Price Objection',
      description: 'Objects to pricing. Practice value framing.',
      difficulty: 'Hard',
      color: 'senary',
      image: '/Too Expensive Tim no backround 2.png', // Selection bubble
      liveSessionImage: '/Too Expensive Tim.png', // During live conversation
    },
    card: {
      age: 44,
      occupation: 'Retail Manager',
      location: 'Budget-conscious household',
      personality: 'Price-sensitive, needs clear ROI justification',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Immediately asks "How much does it cost?"',
        'Compares to cheapest competitors',
        'Needs value breakdown and ROI explanation',
        'Responds to payment plans and guarantees',
      ],
      bestFor: 'Value framing and handling price objections',
      estimatedTime: '7-11 min',
      startingScore: 42,
      targetScore: 72,
      avatar: '💰',
      color: 'yellow',
      elevenAgentId: 'agent_3901k6dtsjyqfvxbxd1pwzzdham0',
    },
  },
  'Spouse Check Susan': {
    bubble: {
      subtitle: 'Decision Maker',
      description: 'Needs partner approval. Practice spouse objection.',
      difficulty: 'Moderate',
      color: 'septenary',
      image: '/Spouse check Susan no backround 2.png',
      liveSessionImage: '/Spouse Check Susan.png',
    },
    card: {
      age: 39,
      occupation: 'Marketing Manager',
      location: 'Two-income household',
      personality: 'Collaborative decision-maker, defers to partner',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says "I need to check with my husband/wife"',
        'Makes joint financial decisions',
        'Needs information to share with spouse',
        'Responds to urgency and limited-time offers',
      ],
      bestFor: 'Overcoming spouse objection and building urgency',
      estimatedTime: '5-8 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '👫',
      color: 'pink',
      elevenAgentId: 'agent_4601k6dvddj8fp89cey35hdj9ef8',
    },
  },
  'Busy Beth': {
    bubble: {
      subtitle: 'Time Crunch',
      description: 'Pressed for time. Practice quick value.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Busy Beth no backround 2.png',
      liveSessionImage: '/Busy Beth.png',
    },
    card: {
      age: 33,
      occupation: 'Emergency Room Nurse',
      location: 'Active household',
      personality: 'Rushed, multitasking, values efficiency',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says "I only have a minute"',
        'Interrupts to speed things up',
        'Appreciates concise, direct communication',
        'Responds to quick value propositions',
      ],
      bestFor: 'Respecting time while delivering value efficiently',
      estimatedTime: '3-6 min',
      startingScore: 52,
      targetScore: 78,
      avatar: '⏰',
      color: 'teal',
      elevenAgentId: 'agent_4801k6dvap8tfnjtgd4f99hhsf10',
    },
  },
  'Renter Randy': {
    bubble: {
      subtitle: 'Authority Question',
      description: 'Renting property. Practice authority objections.',
      difficulty: 'Hard',
      color: 'nonary',
      image: '/Renter randy no backround 2.png',
      liveSessionImage: '/Renter Randy.png',
    },
    card: {
      age: 28,
      occupation: 'Graphic Designer',
      location: 'Rental property',
      personality: 'Uncertain about decision-making authority',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Mentions "I\'m just renting"',
        'Unsure if landlord would approve',
        'Concerned about who pays',
        'Needs guidance on renter vs. owner responsibilities',
      ],
      bestFor: 'Navigating authority objections and landlord dynamics',
      estimatedTime: '6-9 min',
      startingScore: 38,
      targetScore: 68,
      avatar: '🏠',
      color: 'cyan',
      elevenAgentId: 'agent_5701k6dtt9p4f8jbk8rs1akqwtmx',
    },
  },
  'Skeptical Sam': {
    bubble: {
      subtitle: 'Proof Needed',
      description: 'Doubts credibility. Practice trust building.',
      difficulty: 'Hard',
      color: 'denary',
      image: '/Skeptical Sam no backround 2.png',
      liveSessionImage: '/Skeptical Sam.png',
    },
    card: {
      age: 55,
      occupation: 'Retired Police Officer',
      location: 'Security-conscious home',
      personality: 'Suspicious, needs evidence and testimonials',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Questions every claim you make',
        'Asks for proof and references',
        'Wants to see reviews and testimonials',
        'Responds to guarantees and certifications',
      ],
      bestFor: 'Building credibility and using social proof',
      estimatedTime: '8-12 min',
      startingScore: 44,
      targetScore: 74,
      avatar: '🔍',
      color: 'indigo',
      elevenAgentId: 'agent_9201k6dts0haecvssk737vwfjy34',
    },
  },
  'Just Treated Jerry': {
    bubble: {
      subtitle: 'Timing Objection',
      description: 'Recently serviced. Practice timing objections.',
      difficulty: 'Moderate',
      color: 'duodenary',
      image: '/Just treated Jerry no backround 2.png',
      liveSessionImage: '/Just Treated Jerry.png',
    },
    card: {
      age: 46,
      occupation: 'Bank Manager',
      location: 'Well-maintained property',
      personality: 'Organized, plans ahead, timing-focused',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says "We just had pest control done"',
        'Not looking for immediate service',
        'Open to future scheduling',
        'Responds to pre-booking and seasonal offers',
      ],
      bestFor: 'Overcoming timing objections and future booking',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '📅',
      color: 'emerald',
      elevenAgentId: 'agent_8401k6dv9z2kepw86hhe5bvj4djz',
    },
  },
  'Think About It Tina': {
    bubble: {
      subtitle: 'Analysis Paralysis',
      description: 'Needs time to decide. Practice urgency.',
      difficulty: 'Hard',
      color: 'undenary',
      image: '/Think About It Tina no backround.png',
      liveSessionImage: '/Think About It Tina.png',
    },
    card: {
      age: 37,
      occupation: 'Research Analyst',
      location: 'Suburban home',
      personality: 'Analytical, overthinks decisions, risk-averse',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Says "Let me think about it"',
        'Wants to research and compare options',
        'Struggles with decision-making',
        'Responds to limited-time offers and risk reversal',
      ],
      bestFor: 'Creating urgency and overcoming analysis paralysis',
      estimatedTime: '7-10 min',
      startingScore: 46,
      targetScore: 73,
      avatar: '🤔',
      color: 'violet',
      elevenAgentId: 'agent_2501k6btmv4cf2wt8hxxmq4hvzxv',
    },
  },
  'Veteran Victor': {
    bubble: {
      subtitle: 'Military Mindset',
      description: 'Values structure. Practice demonstrating value.',
      difficulty: 'Moderate',
      color: 'primary',
      image: '/Veteran Victor No backround.png',
      liveSessionImage: '/Veteran Victor Landcape.png',
    },
    card: {
      age: 45,
      occupation: 'Retired Military',
      location: 'Suburban home',
      personality: 'Disciplined, values structure and respect, needs clear benefits',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Appreciates respect and professionalism',
        'Values clear, structured communication',
        'Asks about long-term benefits and guarantees',
        'Responds to service-oriented value propositions',
      ],
      bestFor: 'Building rapport with structured communication and respect',
      estimatedTime: '6-9 min',
      startingScore: 50,
      targetScore: 75,
      avatar: '🎖️',
      color: 'blue',
      elevenAgentId: 'agent_3701k8s40awcf30tbs5mrksskzav',
    },
  },
  'I Already Have a Pest Guy': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Most common (60%+). They have someone but haven\'t compared prices in years.',
      difficulty: 'Moderate',
      color: 'secondary',
      image: '/Dan Mitchell.png', // Bubble image for pest industry
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Comfortable with current service, needs convincing to switch',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Has current pest control service',
        'Hasn\'t compared prices in years',
        'Comfortable with status quo',
        'Needs gaps identified in current service',
      ],
      bestFor: 'Finding gaps in current service, competitive positioning',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🏠',
      color: 'blue',
      elevenAgentId: 'placeholder_pest_001',
    },
  },
  'I Don\'t Have Any Bugs': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (40%+). They don\'t see bugs RIGHT NOW.',
      difficulty: 'Moderate',
      color: 'tertiary',
      image: '/Rachel Cooper.png', // Bubble image for pest industry
    },
    card: {
      age: 38,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Reactive mindset, doesn\'t see immediate need',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Doesn\'t see bugs currently',
        'Reactive vs preventative mindset',
        'Questions why pay for something not needed',
        'Responds to preventative value and seasonal pests',
      ],
      bestFor: 'Preventative value, seasonal pest education',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 78,
      avatar: '🐛',
      color: 'green',
      elevenAgentId: 'placeholder_pest_002',
    },
  },
  'How Much Is It?': {
    bubble: {
      subtitle: 'Smokescreen/Qualification',
      description: 'Very common (50%+). Wants to disqualify quickly or price shopping.',
      difficulty: 'Hard',
      color: 'quaternary',
      image: '/Michael Chen.png',
    },
    card: {
      age: 44,
      occupation: 'Budget-conscious homeowner',
      location: 'Various',
      personality: 'Price-focused, wants quick disqualification or genuine price sensitivity',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Asks price immediately',
        'Wants to disqualify quickly OR genuinely price-sensitive',
        'Needs value built before price discussion',
        'Responds to value anchoring',
      ],
      bestFor: 'Building value before price, value anchoring techniques',
      estimatedTime: '7-11 min',
      startingScore: 42,
      targetScore: 72,
      avatar: '💰',
      color: 'yellow',
      elevenAgentId: 'placeholder_pest_003',
    },
  },
  'I Need to Talk to My Spouse': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Very common (40%+). Sometimes legitimate, often an easy exit.',
      difficulty: 'Moderate',
      color: 'quinary',
      // Image handled by industry-specific logic (Windows uses Angela White, Fiber uses Jessica Martinez)
    },
    card: {
      age: 39,
      occupation: 'Homeowner',
      location: 'Family home',
      personality: 'Defers decisions or uses as exit strategy',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says needs to check with spouse',
        'May be legitimate OR easy exit',
        'Not the sole decision maker',
        'Responds to getting spouse involved or follow-up booking',
      ],
      bestFor: 'Handling spouse objection, getting decision makers involved',
      estimatedTime: '5-8 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '👫',
      color: 'pink',
      elevenAgentId: 'placeholder_pest_004',
    },
  },
  'I\'m Renting/Don\'t Own': {
    bubble: {
      subtitle: 'Real Objection/Disqualifier',
      description: 'Common (20-30%). Landlord handles it OR doesn\'t want temporary expense.',
      difficulty: 'Hard',
      color: 'senary',
      image: '/Tyler Jackson.png', // Bubble image for pest industry
    },
    card: {
      age: 28,
      occupation: 'Renter',
      location: 'Rental property',
      personality: 'Not invested in property, sees it as landlord\'s responsibility',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Renting the property',
        'Sees pest control as landlord\'s responsibility',
        'Doesn\'t want temporary expense',
        'Responds to month-to-month and personal comfort value',
      ],
      bestFor: 'Month-to-month service, personal comfort/health emphasis',
      estimatedTime: '6-9 min',
      startingScore: 38,
      targetScore: 68,
      avatar: '🏠',
      color: 'cyan',
      elevenAgentId: 'placeholder_pest_005',
    },
  },
  'I Just Spray Myself': {
    bubble: {
      subtitle: 'Real Objection/DIY Mindset',
      description: 'Common (25%+). Handles it themselves and thinks it\'s working.',
      difficulty: 'Hard',
      color: 'septenary',
      image: '/Greg Wilson.png', // Bubble image for pest industry
    },
    card: {
      age: 48,
      occupation: 'Handy homeowner',
      location: 'Ranch-style home',
      personality: 'DIY-oriented, doesn\'t see professional value',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Uses store-bought sprays',
        'Thinks DIY is working',
        'Doesn\'t see professional value',
        'Responds to professional vs consumer grade products',
      ],
      bestFor: 'Demonstrating professional value over DIY',
      estimatedTime: '6-9 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '🔧',
      color: 'orange',
      elevenAgentId: 'placeholder_pest_006',
    },
  },
  'Send Me Information': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (35%+). Polite way to get you to leave.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Jennifer Lee.png', // Bubble image for pest industry
    },
    card: {
      age: 35,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Polite but not interested, avoids confrontation',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Asks for information/card',
        'Polite way to end conversation',
        'Not actually interested',
        'Responds to specific questions and trial closes',
      ],
      bestFor: 'Overcoming polite brush-offs, trial closing',
      estimatedTime: '4-7 min',
      startingScore: 52,
      targetScore: 78,
      avatar: '📧',
      color: 'teal',
      elevenAgentId: 'placeholder_pest_007',
    },
  },
  'We\'re Selling/Moving Soon': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Moderate (15-20%). Sometimes true, often an excuse.',
      difficulty: 'Moderate',
      color: 'nonary',
      image: '/Chris Bennett.png', // Bubble image for pest industry
    },
    card: {
      age: 45,
      occupation: 'Homeowner',
      location: 'Property for sale',
      personality: 'May be moving OR doesn\'t want to commit',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says selling/moving soon',
        'May be legitimate OR excuse',
        'Doesn\'t want long-term commitment',
        'Responds to month-to-month and property value benefits',
      ],
      bestFor: 'Month-to-month service, property value proposition',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '📦',
      color: 'emerald',
      elevenAgentId: 'placeholder_pest_008',
    },
  },
  'I Have Pets/Kids - Worried About Chemicals': {
    bubble: {
      subtitle: 'Real Concern/Objection',
      description: 'Common (20-25%). Legitimate safety concern with kids/pets.',
      difficulty: 'Moderate',
      color: 'denary',
      image: '/Nicole Rodriguez.png', // Bubble image for pest industry
    },
    card: {
      age: 36,
      occupation: 'Parent/Pet Owner',
      location: 'Family home',
      personality: 'Safety-conscious, prioritizes family/pet safety over pest control',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Has pets and/or young children',
        'Legitimate safety concerns',
        'Cares more about safety than bugs',
        'Responds to pet/kid-safe products and application methods',
      ],
      bestFor: 'Safety-focused selling, pet/kid-safe product education',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🐕',
      color: 'indigo',
      elevenAgentId: 'placeholder_pest_009',
    },
  },
  'Bad Timing - Call Me Back Later': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Common (20%+). Rarely about timing, usually wants you gone.',
      difficulty: 'Moderate',
      color: 'duodenary',
      image: '/Mike Sullivan.png', // Bubble image for pest industry
    },
    card: {
      age: 40,
      occupation: 'Busy homeowner',
      location: 'Active household',
      personality: 'Uses timing as excuse, avoids confrontation',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says bad timing',
        'Rarely actually about timing',
        'Wants you to leave',
        'Responds to quick value hooks and specific callback booking',
      ],
      bestFor: 'Quick value hooks, booking specific callback times',
      estimatedTime: '3-6 min',
      startingScore: 52,
      targetScore: 78,
      avatar: '⏰',
      color: 'violet',
      elevenAgentId: 'placeholder_pest_010',
    },
  },
  'I Already Have Internet': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Most common (70%+). They have service and don\'t see a reason to switch.',
      difficulty: 'Moderate',
      color: 'secondary',
      image: '/Brian Thompson.png',
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Comfortable with current service, needs convincing to switch',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Has current internet service',
        'Doesn\'t see reason to switch',
        'Comfortable with status quo',
        'Needs pain points identified',
      ],
      bestFor: 'Finding pain points, comparing speeds/price, service gaps',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '📡',
      color: 'blue',
      elevenAgentId: 'placeholder_fiber_001',
    },
  },
  'I\'m in a Contract': {
    bubble: {
      subtitle: 'Real Objection',
      description: 'Very common (50%+). Locked in for 12-24 months with early termination fees.',
      difficulty: 'Hard',
      color: 'tertiary',
      image: '/Amanda Stevens.png',
    },
    card: {
      age: 38,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Contract-bound, can\'t afford to break contract',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Locked in contract (12-24 months)',
        'Early termination fees',
        'Can\'t switch even if wanted',
        'Responds to buyout offers and long-term savings',
      ],
      bestFor: 'Pre-qualifying for contract end, buyout offers, long-term savings',
      estimatedTime: '7-10 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '📋',
      color: 'purple',
      elevenAgentId: 'placeholder_fiber_002',
    },
  },
  'I\'m Happy With What I Have': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (50%+). Internet works "well enough" - they don\'t know what they\'re missing.',
      difficulty: 'Moderate',
      color: 'quaternary',
      image: '/Linda Morrison.png',
    },
    card: {
      age: 40,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Satisfied with current service, doesn\'t see need for change',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Internet works "well enough"',
        'Doesn\'t know what they\'re missing',
        'Satisfied with status quo',
        'Responds to uncovering hidden pain points',
      ],
      bestFor: 'Uncovering hidden pain (buffering, lag), work-from-home needs',
      estimatedTime: '6-9 min',
      startingScore: 50,
      targetScore: 78,
      avatar: '😊',
      color: 'green',
      elevenAgentId: 'placeholder_fiber_004',
    },
  },
  'I Just Signed Up': {
    bubble: {
      subtitle: 'Real Objection/Timing',
      description: 'Common (20-25%). Literally just got new service, fresh contract.',
      difficulty: 'Hard',
      color: 'quinary',
      image: '/Marcus Johnson.png',
    },
    card: {
      age: 35,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Just went through setup, worst possible timing',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Just got new service',
        'Fresh contract',
        'Worst possible timing',
        'Responds to contract end date and future pre-qualification',
      ],
      bestFor: 'Getting contract end date, pre-qualifying for future',
      estimatedTime: '5-8 min',
      startingScore: 38,
      targetScore: 68,
      avatar: '📅',
      color: 'orange',
      elevenAgentId: 'placeholder_fiber_006',
    },
  },
  'I Don\'t Want to Deal With Switching': {
    bubble: {
      subtitle: 'Real Objection - Hassle',
      description: 'Common (30%+). Switching seems like too much work.',
      difficulty: 'Moderate',
      color: 'senary',
      image: '/Kevin Richardson.png',
    },
    card: {
      age: 45,
      occupation: 'Busy homeowner',
      location: 'Active household',
      personality: 'Hassle-averse, sees switching as too much work',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Sees switching as too much work',
        'Worried about downtime',
        'Doesn\'t want to call old company',
        'Responds to easy switching and white-glove service',
      ],
      bestFor: 'Making it easy (handle cancellation, same-day install)',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🔄',
      color: 'cyan',
      elevenAgentId: 'placeholder_fiber_007',
    },
  },
  'My Internet Works Fine': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Common (40%+). They don\'t experience obvious problems.',
      difficulty: 'Moderate',
      color: 'septenary',
      image: '/Tom Henderson.png',
    },
    card: {
      age: 37,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Doesn\'t see problems, doesn\'t know internet is slow',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Doesn\'t experience obvious problems',
        'Doesn\'t know internet is slow',
        'No visible issues',
        'Responds to specific scenarios and speed comparisons',
      ],
      bestFor: 'Asking about scenarios (work calls, gaming), comparing speeds',
      estimatedTime: '5-8 min',
      startingScore: 52,
      targetScore: 78,
      avatar: '✅',
      color: 'teal',
      elevenAgentId: 'placeholder_fiber_008',
    },
  },
  'What\'s the Catch?': {
    bubble: {
      subtitle: 'Skepticism/Real Concern',
      description: 'Common (25-30%). Been burned before by hidden fees.',
      difficulty: 'Hard',
      color: 'octonary',
      image: '/Rob Davis.png',
    },
    card: {
      age: 43,
      occupation: 'Skeptical homeowner',
      location: 'Budget-conscious household',
      personality: 'Distrustful, been burned by hidden fees before',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Been burned by hidden fees',
        'Price hikes after promo',
        'Equipment charges',
        'Responds to full transparency and price lock guarantees',
      ],
      bestFor: 'Full transparency, price lock guarantees, no hidden fees',
      estimatedTime: '7-11 min',
      startingScore: 42,
      targetScore: 72,
      avatar: '🤔',
      color: 'yellow',
      elevenAgentId: 'placeholder_fiber_009',
    },
  },
  'I\'m Moving Soon': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Moderate (15-20%). Sometimes true, often an excuse.',
      difficulty: 'Moderate',
      color: 'nonary',
      image: '/Sarah Kim.png',
    },
    card: {
      age: 39,
      occupation: 'Homeowner',
      location: 'Property for sale',
      personality: 'May be moving OR doesn\'t want to commit',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says moving soon',
        'May be legitimate OR excuse',
        'Doesn\'t want commitment',
        'Responds to no contract/month-to-month and transferable service',
      ],
      bestFor: 'No contract options, transferable service, short-term solution',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '📦',
      color: 'emerald',
      elevenAgentId: 'placeholder_fiber_010',
    },
  },
  'My Roof is Fine': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Most common (70%+). They haven\'t inspected it or don\'t see obvious issues.',
      difficulty: 'Moderate',
      color: 'secondary',
      image: '/Mark Patterson.png',
    },
    card: {
      age: 45,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Doesn\'t see damage from ground level, thinks roof is fine',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Haven\'t inspected roof',
        'Don\'t see obvious issues',
        'Thinks roof is fine',
        'Responds to free inspection and visible issues',
      ],
      bestFor: 'Free inspection offer, storm damage education, age/lifespan concerns',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🏠',
      color: 'blue',
      elevenAgentId: 'placeholder_roofing_001',
    },
  },
  'I\'m Not Interested': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (60%+). Roofing reps have bad reputation.',
      difficulty: 'Hard',
      color: 'tertiary',
      // Roofing agent - image removed, will use default or industry-specific
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Assumes you\'re pushy/scammy, hates door-to-door roofers',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Immediate dismissal',
        'Assumes bad reputation',
        'Thinks you\'re pushy/scammy',
        'Responds to pattern interrupts and social proof',
      ],
      bestFor: 'Pattern interrupts, storm damage angle, neighbor social proof',
      estimatedTime: '3-6 min',
      startingScore: 35,
      targetScore: 65,
      avatar: '🚫',
      color: 'red',
      elevenAgentId: 'placeholder_roofing_002',
    },
  },
  'How Much Does a Roof Cost?': {
    bubble: {
      subtitle: 'Smokescreen/Real Concern',
      description: 'Common (40%+). They\'ve heard roofs are expensive and want to disqualify you.',
      difficulty: 'Hard',
      color: 'quaternary',
      image: '/David Kim.png',
    },
    card: {
      age: 48,
      occupation: 'Budget-conscious homeowner',
      location: 'Various',
      personality: 'Price-focused, assumes it\'s too expensive',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Asks price immediately',
        'Assumes too expensive ($10k-$30k+)',
        'Wants to disqualify quickly',
        'Responds to insurance coverage and financing',
      ],
      bestFor: 'Insurance coverage education, financing options, cost of NOT replacing',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '💰',
      color: 'yellow',
      elevenAgentId: 'placeholder_roofing_003',
    },
  },
  'I Just Had My Roof Done': {
    bubble: {
      subtitle: 'Real Objection/Disqualifier',
      description: 'Common (25-30%). Recent replacement or roof is relatively new.',
      difficulty: 'Hard',
      color: 'quinary',
      image: '/Carlos Mendez.png',
    },
    card: {
      age: 40,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Just spent money, worst possible timing',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Recent roof replacement',
        'Roof is relatively new',
        'Just spent money',
        'Responds to storm damage and manufacturer defects',
      ],
      bestFor: 'Storm damage on new roofs, manufacturer defects, free inspection',
      estimatedTime: '5-8 min',
      startingScore: 38,
      targetScore: 68,
      avatar: '🔨',
      color: 'orange',
      elevenAgentId: 'placeholder_roofing_004',
    },
  },
  'I\'ll Call You When I Need a Roof': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (45%+). Polite dismissal - they\'re never calling you.',
      difficulty: 'Moderate',
      color: 'senary',
      image: '/Tom Bradley.png',
    },
    card: {
      age: 44,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Polite but not interested, trying to be nice',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Polite dismissal',
        'Says will call later',
        'Never actually calls',
        'Responds to free inspection and urgency',
      ],
      bestFor: 'Free inspection to know WHEN needed, storm damage urgency',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '📞',
      color: 'cyan',
      elevenAgentId: 'placeholder_roofing_006',
    },
  },
  'I Already Have Someone': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Common (30%+). They used someone 15 years ago or have a "guy" they\'ve never called.',
      difficulty: 'Moderate',
      color: 'septenary',
      image: '/Kevin Anderson.png',
    },
    card: {
      age: 46,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Loyal to old roofer or has easy excuse',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Used someone years ago',
        'Has a "guy" never called',
        'Loyal OR easy excuse',
        'Responds to second opinion and inspection timing',
      ],
      bestFor: 'Second opinion value, when last inspected, insurance specialization',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '👷',
      color: 'teal',
      elevenAgentId: 'placeholder_roofing_007',
    },
  },
  'My Insurance Won\'t Cover It': {
    bubble: {
      subtitle: 'Real Concern/Misconception',
      description: 'Common (35%+). They assume insurance won\'t pay or don\'t know they can file a claim.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Lisa Martinez.png',
    },
    card: {
      age: 43,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Misunderstands insurance, thinks can\'t afford out of pocket',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Assumes insurance won\'t pay',
        'Doesn\'t understand claims',
        'Thinks can\'t afford out of pocket',
        'Responds to insurance education and claim handling',
      ],
      bestFor: 'Insurance claim education, storm damage coverage, handling claims',
      estimatedTime: '6-9 min',
      startingScore: 46,
      targetScore: 74,
      avatar: '🛡️',
      color: 'indigo',
      elevenAgentId: 'placeholder_roofing_008',
    },
  },
  'I\'m Selling Soon': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Moderate (20%+). Sometimes true, often an easy excuse.',
      difficulty: 'Moderate',
      color: 'nonary',
      image: '/Sherry Green.png',
    },
    card: {
      age: 41,
      occupation: 'Homeowner',
      location: 'Property for sale',
      personality: 'May be selling OR doesn\'t want to invest',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says selling soon',
        'May be legitimate OR excuse',
        'Doesn\'t want to invest',
        'Responds to home value increase and sale requirements',
      ],
      bestFor: 'Home value increase, sale inspection requirements, buyer demands',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '🏡',
      color: 'emerald',
      elevenAgentId: 'placeholder_roofing_009',
    },
  },
  'I Don\'t Trust Door-to-Door Roofers': {
    bubble: {
      subtitle: 'Real Concern - Industry Reputation',
      description: 'Common (25-30%). Storm chasers and scammers have ruined D2D roofing reputation.',
      difficulty: 'Hard',
      color: 'denary',
      image: '/Harold Stevens.png',
    },
    card: {
      age: 47,
      occupation: 'Skeptical homeowner',
      location: 'Suburban neighborhood',
      personality: 'Distrustful of door-to-door roofers, assumes scam',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Doesn\'t trust D2D roofers',
        'Assumes scam/rip-off',
        'Industry reputation concerns',
        'Responds to local proof, references, certifications',
      ],
      bestFor: 'Local company proof, references, reviews, certifications, warranties',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '🤨',
      color: 'violet',
      elevenAgentId: 'placeholder_roofing_010',
    },
  },
  'I\'m Not Interested in Solar': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Most common (65%+). Pre-programmed response to solar reps.',
      difficulty: 'Hard',
      color: 'secondary',
      image: '/Gary Thompson.png',
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Pre-programmed response, hasn\'t actually considered solar',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Pre-programmed response',
        'Heard pitch before',
        'Thinks solar reps are annoying',
        'Responds to pattern interrupts and utility bill angle',
      ],
      bestFor: 'Pattern interrupts, utility bill angle, neighbor installs, savings calculator',
      estimatedTime: '4-7 min',
      startingScore: 35,
      targetScore: 65,
      avatar: '☀️',
      color: 'yellow',
      elevenAgentId: 'placeholder_solar_001',
    },
  },
  'Solar is Too Expensive': {
    bubble: {
      subtitle: 'Misconception/Real Concern',
      description: 'Very common (60%+). Think they need $30k-$50k upfront cash.',
      difficulty: 'Hard',
      color: 'tertiary',
      image: '/Brian Walsh.png',
    },
    card: {
      age: 45,
      occupation: 'Budget-conscious homeowner',
      location: 'Suburban home',
      personality: 'Thinks needs huge upfront cash, doesn\'t understand financing',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Thinks needs $30k-$50k upfront',
        'Doesn\'t have that kind of money',
        'Misunderstands financing',
        'Responds to $0 down and lower monthly payment',
      ],
      bestFor: '$0 down education, lower monthly payment, lease vs buy, finance terms',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '💰',
      color: 'orange',
      elevenAgentId: 'placeholder_solar_002',
    },
  },
  'My Electric Bill is Too Low': {
    bubble: {
      subtitle: 'Real Objection - Disqualifier',
      description: 'Common (25-30%). Bill under $100/month, solar doesn\'t make financial sense.',
      difficulty: 'Hard',
      color: 'quaternary',
      image: '/Sarah Chen.png',
    },
    card: {
      age: 38,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Low usage, doesn\'t see financial benefit',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Electric bill under $100/month',
        'Doesn\'t see financial benefit',
        'Savings won\'t justify commitment',
        'Responds to future usage and rising rates',
      ],
      bestFor: 'Future usage (EVs, pool, AC), rising utility rates, small system options',
      estimatedTime: '6-9 min',
      startingScore: 42,
      targetScore: 72,
      avatar: '📊',
      color: 'green',
      elevenAgentId: 'placeholder_solar_006',
    },
  },
  'What If It Doesn\'t Work?': {
    bubble: {
      subtitle: 'Real Concern - Lack of Understanding',
      description: 'Common (30%+). Don\'t understand how solar works.',
      difficulty: 'Moderate',
      color: 'quinary',
      image: '/David Martinez.png',
    },
    card: {
      age: 44,
      occupation: 'Skeptical homeowner',
      location: 'Suburban home',
      personality: 'Doesn\'t trust technology, thinks panels only work in direct sun',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Doesn\'t understand how solar works',
        'Thinks only works in direct sun',
        'Doesn\'t trust technology',
        'Responds to net metering and production guarantees',
      ],
      bestFor: 'Net metering explanation, battery backup, production guarantees, warranties',
      estimatedTime: '6-9 min',
      startingScore: 46,
      targetScore: 74,
      avatar: '❓',
      color: 'cyan',
      elevenAgentId: 'placeholder_solar_007',
    },
  },
  'My Roof is Too Old': {
    bubble: {
      subtitle: 'Real Objection - Legitimate Concern',
      description: 'Common (25%+). Roof is 15-20+ years old, worried about removing panels.',
      difficulty: 'Moderate',
      color: 'senary',
      image: '/Robert Jenkins.png',
    },
    card: {
      age: 47,
      occupation: 'Homeowner',
      location: 'Older home',
      personality: 'Legitimate concern about roof age and panel removal',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Roof is 15-20+ years old',
        'Worried about removing panels later',
        'Can\'t put solar on roof about to replace',
        'Responds to roof inspection and bundled options',
      ],
      bestFor: 'Free roof inspection, bundled roof + solar, roof replacement included',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🏠',
      color: 'teal',
      elevenAgentId: 'placeholder_solar_008',
    },
  },
  'I\'ve Heard Bad Things About Solar': {
    bubble: {
      subtitle: 'Real Concern - Industry Reputation',
      description: 'Common (20-25%). Early solar horror stories, shady companies.',
      difficulty: 'Hard',
      color: 'septenary',
      image: '/Linda Morrison.png',
    },
    card: {
      age: 46,
      occupation: 'Skeptical homeowner',
      location: 'Suburban neighborhood',
      personality: 'Doesn\'t trust industry, heard horror stories',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Heard bad things about solar',
        'Early horror stories',
        'Shady companies, lease nightmares',
        'Responds to company reputation and warranties',
      ],
      bestFor: 'Company reputation/reviews, manufacturer warranties, ownership vs lease',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '⚠️',
      color: 'red',
      elevenAgentId: 'placeholder_solar_009',
    },
  },
  'I Don\'t Qualify': {
    bubble: {
      subtitle: 'Real Objection - Self-Disqualification',
      description: 'Moderate (20%+). Bad credit history or assume they won\'t qualify.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Lamar Johnson.png',
    },
    card: {
      age: 41,
      occupation: 'Homeowner',
      location: 'Various',
      personality: 'Self-disqualifies, assumes can\'t get financing',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Bad credit history',
        'Assumes won\'t qualify',
        'Self-disqualifies',
        'Responds to multiple financing partners and soft credit check',
      ],
      bestFor: 'Multiple financing partners, soft credit check, lease options, cash option',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '📋',
      color: 'indigo',
      elevenAgentId: 'placeholder_solar_010',
    },
  },
  'How Much Does It Cost?': {
    bubble: {
      subtitle: 'Smokescreen/Qualification',
      description: 'Very common (55%+). Want a number to disqualify you or compare.',
      difficulty: 'Hard',
      color: 'quaternary',
      image: '/Kai Shin.png', // Windows agent
    },
    card: {
      age: 44,
      occupation: 'Budget-conscious homeowner',
      location: 'Various',
      personality: 'Price-focused, wants to disqualify or compare prices',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Asks price immediately',
        'Wants number to disqualify',
        'Price shopping',
        'Responds to savings focus and net monthly payment',
      ],
      bestFor: 'Focus on savings not cost, net monthly payment vs current bill',
      estimatedTime: '7-11 min',
      startingScore: 42,
      targetScore: 72,
      avatar: '💰',
      color: 'yellow',
      elevenAgentId: 'placeholder_solar_003',
    },
  },
  'My Windows Are Fine': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Most common (70%+). Windows work (open/close), so they don\'t see a problem.',
      difficulty: 'Moderate',
      color: 'secondary',
      image: '/Robert Lee.png',
    },
    card: {
      age: 45,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Doesn\'t see problem, windows work functionally',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Windows work (open/close)',
        'Don\'t see a problem',
        'Thinks windows are fine',
        'Responds to energy loss and efficiency education',
      ],
      bestFor: 'Energy loss education, drafts, condensation, resale value, age/efficiency',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🪟',
      color: 'blue',
      elevenAgentId: 'placeholder_windows_001',
    },
  },
  'That\'s Too Expensive': {
    bubble: {
      subtitle: 'Real Objection - Sticker Shock',
      description: 'Very common (65%+). $15k-$40k for whole house is legitimately expensive.',
      difficulty: 'Hard',
      color: 'tertiary',
      image: '/Kellie Adams.png',
    },
    card: {
      age: 48,
      occupation: 'Budget-conscious homeowner',
      location: 'Suburban home',
      personality: 'Sticker shock, thinks it\'s too expensive',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Heard price ($15k-$40k)',
        'Sticker shock',
        'Thinks too expensive',
        'Responds to financing and ROI education',
      ],
      bestFor: 'Financing options, energy savings ROI, home value increase, payment plans',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '💸',
      color: 'orange',
      elevenAgentId: 'placeholder_windows_003',
    },
  },
  'I\'m Going to Get Multiple Quotes': {
    bubble: {
      subtitle: 'Real Objection - Smart Consumer',
      description: 'Very common (50%+). Legitimately want to compare 3-5 companies.',
      difficulty: 'Moderate',
      color: 'quaternary',
      image: '/James Porter.png',
    },
    card: {
      age: 43,
      occupation: 'Smart homeowner',
      location: 'Suburban neighborhood',
      personality: 'Wants to compare companies, shopping around',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Wants multiple quotes',
        'Shopping around',
        'Not buying today',
        'Responds to value positioning and comparison education',
      ],
      bestFor: 'Value positioning, apples-to-apples comparison, limited-time incentives',
      estimatedTime: '6-9 min',
      startingScore: 50,
      targetScore: 78,
      avatar: '📋',
      color: 'yellow',
      elevenAgentId: 'placeholder_windows_005',
    },
  },
  'I Just Need One or Two Windows': {
    bubble: {
      subtitle: 'Real Objection - Partial Project',
      description: 'Common (30%+). Want to replace broken/problem windows only.',
      difficulty: 'Moderate',
      color: 'quinary',
      image: '/Michelle Torres.png',
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Wants partial project, not whole house',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Wants 1-2 windows only',
        'Doesn\'t want $30k project',
        'Partial project mindset',
        'Responds to single window pricing and energy loss education',
      ],
      bestFor: 'Single window pricing, energy loss from old windows, staged approach',
      estimatedTime: '5-8 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🪟',
      color: 'cyan',
      elevenAgentId: 'placeholder_windows_006',
    },
  },
  'Just Got New Windows': {
    bubble: {
      subtitle: 'Real Objection/Disqualifier',
      description: 'Common (20-25%). Literally just got new windows installed, worst possible timing.',
      difficulty: 'Hard',
      color: 'quinary',
      image: '/Toby Robin.png',
    },
    card: {
      age: 38,
      occupation: 'Homeowner',
      location: 'Suburban home',
      personality: 'Just spent money, worst possible timing',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Recent window replacement',
        'Just spent money',
        'Worst possible timing',
        'Responds to warranty issues and future needs',
      ],
      bestFor: 'Warranty issues, future needs, additional windows, quality concerns',
      estimatedTime: '5-8 min',
      startingScore: 38,
      targetScore: 68,
      avatar: '🪟',
      color: 'orange',
      elevenAgentId: 'placeholder_windows_007',
    },
  },
  'I\'m Selling/Moving Soon': {
    bubble: {
      subtitle: 'Smokescreen/Real Objection',
      description: 'Common (25%+). Sometimes true, often convenient excuse.',
      difficulty: 'Moderate',
      color: 'nonary',
      image: '/Sherry Green.png', // Windows agent
    },
    card: {
      age: 41,
      occupation: 'Homeowner',
      location: 'Property for sale',
      personality: 'May be selling OR doesn\'t want to invest',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says selling/moving soon',
        'May be legitimate OR excuse',
        'Doesn\'t want to invest',
        'Responds to home value increase and sale requirements',
      ],
      bestFor: 'Home value increase, sale inspection requirements, buyer demands',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '🏡',
      color: 'emerald',
      elevenAgentId: 'placeholder_windows_007',
    },
  },
  'I\'ll Just Do It Myself': {
    bubble: {
      subtitle: 'Real Objection - DIY',
      description: 'Common (25-30%). Handy homeowner or has contractor friend/family.',
      difficulty: 'Moderate',
      color: 'senary',
      image: '/Frank Rodriguez.png',
    },
    card: {
      age: 46,
      occupation: 'Handy homeowner',
      location: 'Suburban neighborhood',
      personality: 'DIY-oriented or has contractor relationship',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Wants to do it themselves',
        'Has contractor friend/family',
        'Thinks can save money',
        'Responds to warranty and professional install value',
      ],
      bestFor: 'Warranty education, professional install critical, manufacturer certification',
      estimatedTime: '6-9 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '🔧',
      color: 'teal',
      elevenAgentId: 'placeholder_windows_008',
    },
  },
  'What\'s Wrong With My Current Windows?': {
    bubble: {
      subtitle: 'Real Objection - Need Education',
      description: 'Common (35%+). Don\'t understand energy loss or how old their windows are.',
      difficulty: 'Moderate',
      color: 'septenary',
      image: '/Patricia Wells.png',
    },
    card: {
      age: 44,
      occupation: 'Homeowner',
      location: 'Older home',
      personality: 'Needs education, doesn\'t see problems',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Doesn\'t understand energy loss',
        'Doesn\'t know window age',
        'Needs education',
        'Responds to energy audit and problem identification',
      ],
      bestFor: 'Energy audit, showing drafts, condensation, noise, comfort issues',
      estimatedTime: '6-9 min',
      startingScore: 50,
      targetScore: 78,
      avatar: '❓',
      color: 'indigo',
      elevenAgentId: 'placeholder_windows_009',
    },
  },
  'I\'m Waiting Until...': {
    bubble: {
      subtitle: 'Smokescreen - Procrastination',
      description: 'Common (40%+). Putting off major expense/decision indefinitely.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Robert Williams.png',
    },
    card: {
      age: 41,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Procrastinates, puts off decision',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Putting off decision',
        'Procrastination',
        'Knows needs it eventually',
        'Responds to urgency and cost of waiting',
      ],
      bestFor: 'Energy loss costs monthly, incentives expiring, financing promotions, comfort urgency',
      estimatedTime: '5-8 min',
      startingScore: 50,
      targetScore: 76,
      avatar: '⏳',
      color: 'violet',
      elevenAgentId: 'placeholder_windows_010',
    },
  },
  'I Don\'t Trust Window Companies': {
    bubble: {
      subtitle: 'Real Concern - Industry Reputation',
      description: 'Common (25-30%). Window companies have reputation issues - scammers, high-pressure sales, poor quality.',
      difficulty: 'Hard',
      color: 'denary',
      image: '/Arron Black.png',
    },
    card: {
      age: 46,
      occupation: 'Skeptical homeowner',
      location: 'Suburban neighborhood',
      personality: 'Distrustful of window companies, assumes scam or poor quality',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Doesn\'t trust window companies',
        'Assumes scam/rip-off/poor quality',
        'Industry reputation concerns',
        'Responds to local proof, references, certifications',
      ],
      bestFor: 'Local company proof, references, reviews, certifications, warranties, BBB rating',
      estimatedTime: '7-11 min',
      startingScore: 40,
      targetScore: 70,
      avatar: '🤨',
      color: 'violet',
      elevenAgentId: 'placeholder_windows_011',
    },
  },
  'I\'m Not Interested': {
    bubble: {
      subtitle: 'Smokescreen',
      description: 'Very common (60%+). Window companies have bad reputation.',
      difficulty: 'Hard',
      color: 'tertiary',
      image: '/Lewis McArthur.png', // Windows agent
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Assumes you\'re pushy/scammy, hates door-to-door window companies',
      challengeLevel: 3,
      challengeLabel: 'Hard',
      difficultyKey: 'hard',
      traits: [
        'Immediate dismissal',
        'Assumes bad reputation',
        'Thinks you\'re pushy/scammy',
        'Responds to pattern interrupts and social proof',
      ],
      bestFor: 'Pattern interrupts, energy savings angle, neighbor social proof',
      estimatedTime: '3-6 min',
      startingScore: 35,
      targetScore: 65,
      avatar: '🚫',
      color: 'red',
      elevenAgentId: 'placeholder_windows_012',
    },
  },
  'Not the Right Time / Maybe Next Year': {
    bubble: {
      subtitle: 'Timing Objection',
      description: 'Common (30%+). Says it\'s not the right time or maybe next year. Often a smokescreen for other concerns.',
      difficulty: 'Moderate',
      color: 'octonary',
      image: '/Steve Harry.png',
      liveSessionImage: '/Steve Harry.png',
    },
    card: {
      age: 44,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Uses timing as excuse, avoids commitment',
      challengeLevel: 2,
      challengeLabel: 'Moderate',
      difficultyKey: 'moderate',
      traits: [
        'Says "not the right time" or "maybe next year"',
        'Often a smokescreen for other concerns',
        'Avoids making a decision',
        'Responds to urgency and immediate benefits',
      ],
      bestFor: 'Creating urgency, addressing underlying concerns, immediate value propositions',
      estimatedTime: '5-8 min',
      startingScore: 48,
      targetScore: 75,
      avatar: '📅',
      color: 'violet',
      elevenAgentId: 'placeholder_timing_001',
    },
  },
  'Angry Indian': {
    bubble: {
      subtitle: 'Confrontational',
      description: 'Angry and confrontational homeowner. Tests your ability to handle difficult situations and maintain professionalism under pressure.',
      difficulty: 'Expert',
      color: 'primary',
      image: '/angry-indian.png',
      liveSessionImage: '/angry-indian.png',
    },
    card: {
      age: 42,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Angry and confrontational, tests professionalism under pressure',
      challengeLevel: 5,
      challengeLabel: 'Expert',
      difficultyKey: 'expert',
      traits: [
        'Starts conversation angry or confrontational',
        'Tests your ability to stay calm',
        'Challenges your professionalism',
        'Responds to empathy and de-escalation',
      ],
      bestFor: 'Handling difficult situations and maintaining professionalism under pressure',
      estimatedTime: '5-10 min',
      startingScore: 30,
      targetScore: 65,
      avatar: '😠',
      color: 'red',
      mostChallenging: true,
      elevenAgentId: 'agent_3301kf4hmz0qfcdsms0djvq8wf2z',
    },
  },
  'The Karen': {
    bubble: {
      subtitle: 'Demanding & Entitled',
      description: 'Demanding, entitled, and difficult homeowner. Tests your patience and ability to handle unreasonable requests while maintaining professionalism.',
      difficulty: 'Expert',
      color: 'primary',
      image: '/The Karen.png',
      liveSessionImage: '/The Karen.png',
    },
    card: {
      age: 45,
      occupation: 'Homeowner',
      location: 'Suburban neighborhood',
      personality: 'Demanding, entitled, and difficult. Tests patience and professionalism',
      challengeLevel: 5,
      challengeLabel: 'Expert',
      difficultyKey: 'expert',
      traits: [
        'Makes unreasonable demands',
        'Tests your patience constantly',
        'Entitled attitude and expectations',
        'Responds to firm boundaries and professional assertiveness',
      ],
      bestFor: 'Handling difficult customers and maintaining professionalism with demanding personalities',
      estimatedTime: '5-10 min',
      startingScore: 30,
      targetScore: 65,
      avatar: '😤',
      color: 'red',
      mostChallenging: true,
      elevenAgentId: 'placeholder_karen_001',
    },
  },
  // TEMPORARILY REMOVED: 'English Second Language Elena' - can be restored by adding back to ALLOWED_AGENT_ORDER and uncommenting below
  // 'English Second Language Elena': {
  //   bubble: {
  //     subtitle: 'Language Barrier',
  //     description: 'Language barrier present. Practice clear communication.',
  //     difficulty: 'Moderate',
  //     color: 'secondary',
  //     image: '/agents/elena.png',
  //     liveSessionImage: '/agents/elena.png',
  //   },
  //   card: {
  //     age: 38,
  //     occupation: 'Restaurant Manager',
  //     location: 'Multicultural neighborhood',
  //     personality: 'Patient but needs simple, clear explanations',
  //     challengeLevel: 2,
  //     challengeLabel: 'Moderate',
  //     difficultyKey: 'moderate',
  //     traits: [
  //       'May ask for clarification frequently',
  //       'Needs simple, clear language',
  //       'Responds well to visual aids and demonstrations',
  //       'Appreciates patience and respect',
  //     ],
  //     bestFor: 'Practicing clear communication and cultural sensitivity',
  //     estimatedTime: '7-10 min',
  //     startingScore: 48,
  //     targetScore: 76,
  //     avatar: '🌍',
  //     color: 'teal',
  //     elevenAgentId: 'agent_5901k8s3rnrkfp9vky7q1j4t3xhj',
  //   },
  // },
  // REMOVED: 'Tag Team Tanya & Tom' - audio unavailable, removed from landing page voice test
  // 'Tag Team Tanya & Tom': {
  //   bubble: {
  //     subtitle: 'Couple Decision',
  //     description: 'Multiple decision-makers. Practice consensus.',
  //     difficulty: 'Hard',
  //     color: 'tertiary',
  //     image: '/Tanya and Tom no backround.png', // Bubble image (no background)
  //     liveSessionImage: '/tanya and tom.png', // Live session image
  //   },
  //   card: {
  //     age: 42,
  //     occupation: 'Both work full-time',
  //     location: 'Family home',
  //     personality: 'Collaborative decision-makers, need both to agree',
  //     challengeLevel: 3,
  //     challengeLabel: 'Hard',
  //     difficultyKey: 'hard',
  //     traits: [
  //       'Both partners ask different questions',
  //       'Need to address concerns of both individuals',
  //       'May disagree with each other during conversation',
  //       'Requires building consensus and addressing dual objections',
  //     ],
  //     bestFor: 'Handling multiple decision-makers and building consensus',
  //     estimatedTime: '9-13 min',
  //     startingScore: 44,
  //     targetScore: 72,
  //     avatar: '👥',
  //     color: 'purple',
  //     elevenAgentId: 'agent_4301k8s3mmvvekqb6fdpyszs9md4',
  //   },
  // },
  // TEMPORARILY REMOVED: 'Comparing Carl' - can be restored by adding back to ALLOWED_AGENT_ORDER and uncommenting below
  // 'Comparing Carl': {
  //   bubble: {
  //     subtitle: 'Price Shopper',
  //     description: 'Wants to compare options. Practice competitive positioning.',
  //     difficulty: 'Hard',
  //     color: 'quaternary',
  //     image: '/agents/carl.png',
  //     liveSessionImage: '/agents/carl.png',
  //   },
  //   card: {
  //     age: 47,
  //     occupation: 'Purchasing Manager',
  //     location: 'Budget-conscious household',
  //     personality: 'Analytical, compares everything, price-focused',
  //     challengeLevel: 3,
  //     challengeLabel: 'Hard',
  //     difficultyKey: 'hard',
  //     traits: [
  //       'Says "Let me compare your prices with others"',
  //       'Wants detailed breakdowns and written quotes',
  //       'Questions value of premium features',
  //       'Responds to limited-time offers and competitive positioning',
  //     ],
  //     bestFor: 'Handling comparison objections and demonstrating unique value',
  //     estimatedTime: '8-12 min',
  //     startingScore: 43,
  //     targetScore: 73,
  //     avatar: '⚖️',
  //     color: 'amber',
  //     elevenAgentId: 'agent_5301k8s3gw9zf6jsmp2bfw7v7crn',
  //   },
  // },
}